### ISSUE TITLE
Baolei-Man

### ISSUE THREAD

**Issue by gteniou** [haudiobe/5G-Video-Content#1]
**Contact Person**
Gilles Teniou, teniou@tencent.com

**Related Scenario**
Online Gaming

**Accessibility of Sequence**
https://tencenteuropeoa-my.sharepoint.com/personal/teniou_tencenteuropeoa_onmicrosoft_com/_layouts/15/onedrive.aspx?id=%2Fpersonal%2Fteniou%5Ftencenteuropeoa%5Fonmicrosoft%5Fcom%2FDocuments%2FGaming%20sequences%2FYUVSequences%2Fbaolei%5F1920x1080%5F60fps%5F01%2Eyuv&parent=%2Fpersonal%2Fteniou%5Ftencenteuropeoa%5Fonmicrosoft%5Fcom%2FDocuments%2FGaming%20sequences%2FYUVSequences&originalPath=aHR0cHM6Ly90ZW5jZW50ZXVyb3Blb2EtbXkuc2hhcmVwb2ludC5jb20vOnU6L2cvcGVyc29uYWwvdGVuaW91X3RlbmNlbnRldXJvcGVvYV9vbm1pY3Jvc29mdF9jb20vRVpEYlFwNXF2dkpQcUtzd0c0Y1gyS0VCSkE4ZlQwQjRHSmM3STgxTG91Wl94Zz9ydGltZT1sdHlrWWxxVjJFZw

**Copyright/License**
Copyright © 1998 - 2020 Tencent. All Rights Reserved.
This sequence and all intellectual property rights therein remain the property of Shenzhen Tencent Computer System Co. Ltd.. This sequence may only be used for the purpose of developing, testing and promulgating technology standards (the Purpose). Shenzhen Tencent Computer System Co. Ltd. make no warranties with respect to this sequence and expressly disclaim any warranties regarding its fitness for any purpose. This disclaimer shall remain attached to this sequence except when this sequence is used for the Purpose.

**Status**
already agreed as reference sequence

**Metadata**
Resolution | 1920x1080
Scan | Progressive
Frame Rate | 60 fps
Bit Depth | 8
Length | 600 frames
YUV format | YUV 4:2:0
Color components | Y’CbCr
Colour space | BT.709

**MD5 Hash**
MD5 (baolei_1920x1080_60fps_01.yuv) = 6b41e581136cef2a9bd92259237736bf

**Comment by gteniou** [comment]
```javascript
    {
      "Sequence": {
        "Name": "Baolei-Man",
        "Background": "The Baolei-Man test sequence is an extract from a famous online multiplayer game in which many players play in a battle royale mode meaning that in survival mode, the last standing one is the winner.",
        "Scenario": "Gaming",
        "Key": "S5-R2",
        "URI": "./baolei-man.yuv",
        "md5": "6b41e581136cef2a9bd92259237736bf",
        "thumbnail": "./baolei-man.png",
        "preview": "./baolei-man.mp4"
      },
      "Properties": {
        "width": 1920,
        "height": 1080,
        "format": "yuv",
        "packing": "planar",
        "scan": "progressive",
        "subsampling": "420",
        "bitDepth": 8,
        "frameRate": 60,
        "colourPrimaries": 1,
        "transferCharacteristics": 1,
        "matrixCoefficients": 1,
        "sampleAspectRatio": 1,
        "duration": 10,
        "frameCount": 600
      },
      "copyRight": "Copyright © 1998 - 2020 Tencent. All Rights Reserved. This sequence and all intellectual property rights therein remain the property of Shenzhen Tencent Computer System Co. Ltd.. This sequence may only be used for the purpose of developing, testing and promulgating technology standards (the Purpose). Shenzhen Tencent Computer System Co. Ltd. make no warranties with respect to this sequence and expressly disclaim any warranties regarding its fitness for any purpose. This disclaimer shall remain attached to this sequence except when this sequence is used for the Purpose.",
      "Contact": {
        "Name": "Gilles Teniou",
        "Company": "Tencent",
        "e-mail": "teniou@tencent.com"
      }
    }
```

**Comment by gteniou** [comment]
In http://dash.akamaized.net/WAVE/3GPP/5GVideo/ReferenceSequences/Baolei-Man/
The key is missing and the frame count should be 600 (60fps ; 10s)

**Comment by haudiobe** [comment]
Uploaded - please verify http://dash.akamaized.net/WAVE/3GPP/5GVideo/ReferenceSequences/Baolei-Man/

**Comment by gteniou** [comment]
You can copy-paste the JSON above. Key is missing and frame count incorrect

**Comment by gteniou** [comment]
JSON file **INCORRECT** (key S5-R2 missing and framcount 600 instead of 30
YUV file downloaded - MD5 OK
mp4 preview OK
png preview OK

**Comment by gteniou** [comment]
JSON file OK
