### ISSUE TITLE
wrong sequence/JSON/png for WoW

### ISSUE THREAD

**Issue by ca-ga-ma** [haudiobe/5G-Video-Content#27]
We have selected WoW_Part2 in the TR.
on the Akamai server, the PNG corresponds to WoW_Part2, but the mp4, MD5 and possibly the YUV correspond to WoW_Part1.
The correct sequence should be uploaded and the mp4 and MD5 corrected.

**Comment by haudiobe** [comment]
Downloaded, shorted to 10 sec. md5 checked. MP4 generated. All available here: https://dash-large-files.akamaized.net/WAVE/3GPP/5GVideo/ReferenceSequences/World-of-WarCraft/World-of-WarCraft.json - yuv needs 20min to upload.

**Comment by ca-ga-ma** [comment]
md5 OK, mp4 OK, YUV ok.
