### ISSUE TITLE
Baolei-Woman

### ISSUE THREAD

**Issue by gteniou** [haudiobe/5G-Video-Content#4]
**Link to YUV:** 
https://tencenteuropeoa-my.sharepoint.com/:u:/g/personal/teniou_tencenteuropeoa_onmicrosoft_com/EW0ikj9jDhBGm8E8B-TP_dABVwITDxxuF0S2e6UStxEzIA

**Link to MP4 preview:** 
https://tencenteuropeoa-my.sharepoint.com/:v:/g/personal/teniou_tencenteuropeoa_onmicrosoft_com/EUz7h5TNHpVCjkNRJb2KEiIBX1PiSPnjyj5iYK2RYwzlsg

**Link to PNG preview:**
https://tencenteuropeoa-my.sharepoint.com/:i:/g/personal/teniou_tencenteuropeoa_onmicrosoft_com/Ebm6N4uMDQ9GkKXPkDBuq1UBBd0fo6Lu4EyQ3CTzNSysqg

```javascript
    {
      "Sequence": {
        "Name": "Baolei-Woman",
        "Background": "The Baolei-Woman test sequence is an extract from a famous online multiplayer game in which many players play in a battle royale mode meaning that in survival mode, the last standing one is the winner.",
        "Scenario": "Gaming",
        "Key": "S5-R3",
        "URI": "./baolei-woman.yuv",
        "md5": "cd279102ed3c0f30647871d92a098eed",
        "thumbnail": "./baolei-woman.png",
        "preview": "./baolei-woman.mp4"
      },
      "Properties": {
        "width": 1920,
        "height": 1080,
        "format": "yuv",
        "packing": "planar",
        "scan": "progressive",
        "subsampling": "420",
        "bitDepth": 8,
        "frameRate": 60,
        "colourPrimaries": 1,
        "transferCharacteristics": 1,
        "matrixCoefficients": 1,
        "sampleAspectRatio": 1,
        "duration": 10,
        "frameCount": 600
      },
      "copyRight": "Copyright © 1998 - 2020 Tencent. All Rights Reserved. This sequence and all intellectual property rights therein remain the property of Shenzhen Tencent Computer System Co. Ltd.. This sequence may only be used for the purpose of developing, testing and promulgating technology standards (the Purpose). Shenzhen Tencent Computer System Co. Ltd. make no warranties with respect to this sequence and expressly disclaim any warranties regarding its fitness for any purpose. This disclaimer shall remain attached to this sequence except when this sequence is used for the Purpose.",
      "Contact": {
        "Name": "Gilles Teniou",
        "Company": "Tencent",
        "e-mail": "teniou@tencent.com"
      }
    }
```

**Comment by haudiobe** [comment]
Uploaded - please verify http://dash.akamaized.net/WAVE/3GPP/5GVideo/ReferenceSequences/Baolei-Woman/

**Comment by gteniou** [comment]
JASON OK
yuv file downloaded - MD5 OK

**Comment by gteniou** [comment]
The YUV file is wrong. This is Baolei man.

**Comment by gteniou** [comment]
Still Wrong YUV file

**Comment by haudiobe** [comment]
Uploading now - available in 3 hours

**Comment by ca-ga-ma** [comment]
the MD5 in the JSON for Baolei-Woman is incorrect  as it is identical to the one for 4K-Yard. (that is the correct one for 4K-Yard).

**Comment by ca-ga-ma** [comment]
but the MD5 provided by Gilles at the top of this thread is correct
""md5": "cd279102ed3c0f30647871d92a098eed"

**Comment by haudiobe** [comment]
Fixed, please check. https://dash-large-files.akamaized.net/WAVE/3GPP/5GVideo/ReferenceSequences/Baolei-Woman/Baolei-Woman.json

**Comment by ca-ga-ma** [comment]
yes, seems correct now. thanks.

**Comment by gteniou** [comment]
correct link to the YUV source file
Baolei-woman YUV : https://tencenteuropeoa-my.sharepoint.com/:u:/g/personal/teniou_tencenteuropeoa_onmicrosoft_com/ERt4MP5RHLRClZ11-GaMpJIBp4qoNw6MfS6D9m9dOlhfpg

**Comment by gteniou** [comment]
all good in https://dash-large-files.akamaized.net/WAVE/3GPP/5GVideo/ReferenceSequences/Baolei-Woman/
but I thought http://dash.akamaized.net/WAVE/3GPP/5GVideo/ReferenceSequences/Baolei-Woman/ was a mirror, it is not... only dash-large-files... is the right link
