### ISSUE TITLE
Jianling-temple

### ISSUE THREAD

**Issue by gteniou** [haudiobe/5G-Video-Content#7]
**Link to YUV:** 
https://tencenteuropeoa-my.sharepoint.com/:u:/g/personal/teniou_tencenteuropeoa_onmicrosoft_com/EWdiqrxVabxMlFUB1MVPmewB7f95zLvdkX5ZDznYxtEaOw

**Link to MP4 preview:** 
https://tencenteuropeoa-my.sharepoint.com/:v:/g/personal/teniou_tencenteuropeoa_onmicrosoft_com/EX3KpvnpgTtLh6qhDI_4fMMBkkxl643B8rVqetnwukfp0g

**Link to PNG preview:**
https://tencenteuropeoa-my.sharepoint.com/:i:/g/personal/teniou_tencenteuropeoa_onmicrosoft_com/EYkhdEc5iF9OhI6U1wbZfsEBvWeS3sczhczT-iSKH0jylQ

```javascript
    {
      "Sequence": {
        "Name": "Jianling-temple",
        "Background": "The Jianling-Temple test sequence is an extract from a famous massive multiplayer online role-playing game (MMORPG) having two gameplay modes Player-versus-Environment (PvE) and Player-versus-player (PvP).",
        "Scenario": "Gaming",
        "Key": "S5-R6",
        "URI": "./Jianling-temple.yuv",
        "md5": "408e5ed2c441a2fe71a6653615c9489d",
        "thumbnail": "./Jianling-temple.png",
        "preview": "./Jianling-temple.mp4"
      },
      "Properties": {
        "width": 1920,
        "height": 1080,
        "format": "yuv",
        "packing": "planar",
        "scan": "progressive",
        "subsampling": "420",
        "bitDepth": 8,
        "frameRate": 60,
        "colourPrimaries": 1,
        "transferCharacteristics": 1,
        "matrixCoefficients": 1,
        "sampleAspectRatio": 1,
        "duration": 10,
        "frameCount": 600
      },
      "copyRight": "Copyright © 1998 - 2020 Tencent & NCSOFT. All Rights Reserved. This sequence and all intellectual property rights therein remain the property of Shenzhen Tencent Computer System Co. Ltd. and NCSOFT Co.Ltd.. This sequence may only be used for the purpose of developing, testing and promulgating technology standards (the Purpose). Shenzhen Tencent Computer System Co. Ltd. and NCSOFT Co.Ltd. make no warranties with respect to this sequence and expressly disclaim any warranties regarding its fitness for any purpose. This disclaimer shall remain attached to this sequence except when this sequence is used for the Purpose.",
      "Contact": {
        "Name": "Gilles Teniou",
        "Company": "Tencent",
        "e-mail": "teniou@tencent.com"
      }
    }
```

**Comment by haudiobe** [comment]
Uploaded - please verify http://dash.akamaized.net/WAVE/3GPP/5GVideo/ReferenceSequences/Jiangling-temple/

**Comment by gteniou** [comment]
Cannot access the link.
This is not Jiangling but **Jianling**. There are also typos I tried to correct in the TR.

**Comment by haudiobe** [comment]
http://dash.akamaized.net/WAVE/3GPP/5GVideo/ReferenceSequences/Jianling-Temple

**Comment by gteniou** [comment]
JSON: should change Jianling into jianling for the file names. UNIX/MAC are case sensitive and scripts may not work.
Downloaded YUV file: MD5 OK
Please change jianling_temple.yuv into jianling-temple.yuv (dash instead of underscore) same for .mp4

**Comment by haudiobe** [comment]
http://dash.akamaized.net/WAVE/3GPP/5GVideo/ReferenceSequences/Baolei-Yard/

**Comment by gteniou** [comment]
1) Please rename files with capital "J" (**json, png and yuv**)
2) please rename files with "-" instead of "_" (**mp4 and yuv**)

**Comment by haudiobe** [comment]
Renamed everything to Jianling-Temple

**Comment by gteniou** [comment]
All good Thank you
